### PR TITLE
release: Bump to v2.1.0

### PR DESCRIPTION
**Pull request by netoax**

### CODE REVIEW

**Comment by lcbm** [comment]
LGTM, im just wondering if we should wait on some PRs and rebase before making a release!

**Comment by netoax** [comment]
> LGTM, im just wondering if we should wait on some PRs and rebase before making a release!

Why should we wait? I didn't get your point. BTW, libraries are already published on NPM, the release was done. In general, they can be released without worries (when there are no breaking changes).

**Review by lcbm — APPROVED** [review]
My point was to not have to go through the release process again later this week (or next) when the PRs are approved, but I guess it doesn't matter lol.

**Comment by netoax** [comment]
> again later this week (or next) when the PRs are approved, but I guess it doesn't matter lol.

Ah, make sense. In this case, there's no problem because they're libraries and sometimes other PRs (such as the CLI one) are depending on recently added features.

**Pull request merged**
